extends HTTPRequest

# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/OpenAPITools/openapi-generator.git
"""


export(String) var private_key
export(String) var game_id
export(String) var base_url
export(bool) var ssl_validate_domain
export(bool) var validate

var username_cache
var token_cache
var request_type

var busy = false

preload("../Models/user.gd")
var unirest = preload("../unirest.gd")

"""Create user

This can only be done by the logged in user.
:param User body: Created user object (required)
"""

func create_user(User body, header = {}, auth = null, callback = null):
    var params : String

    unirest.post(base_url + "/user", params, header, auth, callback)

"""Creates list of users with given input array

:param Array body: List of user object (required)
"""

func create_users_with_array_input(Array body, header = {}, auth = null, callback = null):
    var params : String

    unirest.post(base_url + "/user/createWithArray", params, header, auth, callback)

"""Creates list of users with given input array

:param Array body: List of user object (required)
"""

func create_users_with_list_input(Array body, header = {}, auth = null, callback = null):
    var params : String

    unirest.post(base_url + "/user/createWithList", params, header, auth, callback)

"""Delete user

This can only be done by the logged in user.
:param String username: The name that needs to be deleted (required)
"""

func delete_user(String username, header = {}, auth = null, callback = null):
    var params : String

    unirest.delete(base_url + "/user/{username}", params, header, auth, callback)

"""Get user by user name

:param String username: The name that needs to be fetched. Use user1 for testing. (required)
"""

func get_user_by_name(String username, header = {}, auth = null, callback = null):
    var params : String

    unirest.get(base_url + "/user/{username}", params, header, auth, callback)

"""Logs user into the system

:param String username: The user name for login (required)
:param String password: The password for login in clear text (required)
"""

func login_user(String username, String password, header = {}, auth = null, callback = null):
    var params : String
    params += "?"
    for i in range(0, username.size():    
        params += "username=" + name
        if i != username.size() - 1:
            params += "&"
    params += "?"
    for i in range(0, password.size():    
        params += "password=" + name
        if i != password.size() - 1:
            params += "&"

    unirest.get(base_url + "/user/login", params, header, auth, callback)

"""Logs out current logged in user session

"""

func logout_user(header = {}, auth = null, callback = null):
    var params : String

    unirest.get(base_url + "/user/logout", params, header, auth, callback)

"""Updated user

This can only be done by the logged in user.
:param String username: name that need to be deleted (required)
:param User body: Updated user object (required)
"""

func update_user(String username, User body, header = {}, auth = null, callback = null):
    var params : String

    unirest.put(base_url + "/user/{username}", params, header, auth, callback)

